services:
  jenkins:
    build: .
    user: root
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPS=-Xmx2g
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    ports:
      - 8181:8080
      - 50000:50000
    restart: unless-stopped